---
# tasks file for centos-kubernetes
- name: == SYSTEM == Turn Off SELinux
  selinux:
    state: disabled

- name: == REPO == Add Kubernetes Repository
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo

- name: == YUM == Install Kubernetes
  yum: name={{ item }} state=latest
  with_items: "{{ kubernetes_items }}"

- name: == SERVICE == Enable/Start Kubelet Service
  raw: systemctl enable kubelet && systemctl start kubelet

- name: == SERVICE == Make sure Kubelet is running
  service:
    name: kubelet
    enabled: yes
    state: started
